### PR TITLE
Support options.customBlockFn

### PR DESCRIPTION
**Pull request by sstur**
This aims to implement the functionality of #24. Not yet complete.

### CODE REVIEW

**Comment by AGresvig** [comment]
Fantastic! This'll help us implement text-alignment support..
What remains, only tests?

**Comment by frenzzy** [comment]
@sstur @dfwood90 any updates on this?

**Comment by sstur** [comment]
Done. Tests have been added and this has been published to npm.

**Comment by AGresvig** [comment]
Great, thanks!

**Pull request merged**
