### PR TITLE
Support custom block types

### PR DESCRIPTION
**Pull request by blittle**
This can be used in concordance with https://github.com/sstur/draft-js-export-html#blockrenderers

### CODE REVIEW

**Comment by mdarcemont** [comment]
I'm very interested in this pull request.
@sstur Is there a reason for the fact it's not merged yet ?

**Comment by sstur** [comment]
Sorry for the delay. There is no good reason why this isn't merged yet. Just that I've been bad at reviewing all the issues and pull requests for a bunch of open-source projects.

This PR looks good. Thanks to @blittle for the contribution!

**Comment by mdarcemont** [comment]
Thank you !
I hope you'll have time to publish new version with this enhancement soon !

**Comment by sstur** [comment]
@mdarcemont Done.

**Pull request merged**
